name: Project Name
title: Baked with Awestruct
org: Organization
base_url: ''
profiles:
  production:
    base_url: http://ankur786arya.github.io
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: master
      # use master branch for <username>.github.io repository
      #branch: master